troubleshooting

diff --git a/ci/speech_batch_kit_sanity_test b/ci/speech_batch_kit_sanity_test
--- a/ci/speech_batch_kit_sanity_test
+++ b/ci/speech_batch_kit_sanity_test
@@ -11,13 +11,14 @@ docker_port_1="5000"
 docker_port_2="5001"
 container_port="5000"
 temp_vol="test_vol"
+# containerRegistryName="joshcacr.azurecr.io"
 
 # pull speech-to-text Docker image
 docker pull $sttImageName
 
 # run 2x speech-to-text Docker containers exposed on Docker ports 5000 and 5001 
-docker run --name $stt_on_prem_1 -it -d --rm -p $docker_port_1:$container_port --memory 4g --cpus 2 $sttImageName eula=accept Billing='https://westus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken' Apikey='28c6cec5a7544cf8b1f7cf3427d4be09' CloudAI:SentimentAnalysisSettings:TextAnalyticsHost='https://westus2.api.cognitive.microsoft.com/text/analytics/v3.0/sentiment' CloudAI:SentimentAnalysisSettings:SentimentAnalysisApiKey='286be3fde35540b09d8c34f2a71224f3'
-docker run --name $stt_on_prem_2 -it -d --rm -p $docker_port_2:$container_port --memory 4g --cpus 2 $sttImageName eula=accept Billing='https://westus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken' Apikey='28c6cec5a7544cf8b1f7cf3427d4be09' CloudAI:SentimentAnalysisSettings:TextAnalyticsHost='https://westus2.api.cognitive.microsoft.com/text/analytics/v3.0/sentiment' CloudAI:SentimentAnalysisSettings:SentimentAnalysisApiKey='286be3fde35540b09d8c34f2a71224f3'
+docker run --name $stt_on_prem_1 -it -d --rm -p $docker_port_1:$container_port --memory 4g --cpus 2 $sttImageName eula=accept Billing='https://westus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken' Apikey='28c6cec5a7544cf8b1f7cf3427d4be09'
+docker run --name $stt_on_prem_2 -it -d --rm -p $docker_port_2:$container_port --memory 4g --cpus 2 $sttImageName eula=accept Billing='https://westus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken' Apikey='28c6cec5a7544cf8b1f7cf3427d4be09'
 
 # get IP addresses of speech-to-text containers when available
 finished=0
@@ -26,9 +27,9 @@ while [[ $finished != 1 ]]; do
     if [ $response = "200" ]; then
         let finished=1
         ip1=$(docker inspect $stt_on_prem_1 --format '{{ .NetworkSettings.IPAddress }}')
-        echo INFO: Fetched IP address of first speech-to-text container
+        echo "INFO: Fetched IP address of first speech-to-text container"
     else
-        echo INFO: Waiting for first speech-to-text container to start
+        echo "INFO: Waiting for first speech-to-text container to start"
     fi
     sleep 1
 done
@@ -39,9 +40,9 @@ while [[ $finished != 1 ]]; do
     if [ $response = "200" ]; then
         let finished=1
         ip2=$(docker inspect $stt_on_prem_2 --format '{{ .NetworkSettings.IPAddress }}')
-        echo INFO: Fetched IP address of second speech-to-text container
+        echo "INFO: Fetched IP address of second speech-to-text container"
     else
-        echo INFO: Waiting for second speech-to-text container to start
+        echo "INFO: Waiting for second speech-to-text container to start"
     fi
     sleep 1
 done
@@ -49,7 +50,7 @@ done
 # update config.yaml with speech container IP addresses 
 pushd $temp_vol
 
-sudo rm test_config.yaml
+sudo rm -f test_config.yaml
 echo "MyContainer1:
   concurrency: 2
   host: $ip1
@@ -61,11 +62,12 @@ MyContainer2:
 popd
 
 # run batch processing container. container deleted after running
-echo INFO: Sleeping for 15 seconds while waiting for speech-to-text containers to be ready
+echo "INFO: Sleeping for 15 seconds while waiting for BOTH speech-to-text containers to be ready"
 sleep 15
 docker run --rm --name batch_processing --volume "$(pwd)"/$temp_vol:/my_nfs --net=host $containerRegistryName/batchkit/speech-batch-kit:test -config /my_nfs/test_config.yaml -input_folder /my_nfs/test_audio_files -output_folder /my_nfs/transcriptions -log_folder /my_nfs/logs -file_log_level DEBUG -nbest 1 -m ONESHOT -diarization None -language en-US -strict_config -console_log_level DEBUG
 
 pushd $temp_vol/transcriptions
+EXIT=false 
 
 # fetch the number of IP address endpoints, number of audio files that were successfully processed, and total number of processed audio files from the speech-batch-kit container logs
 # if container did not start properly, all of the commands below will fail, and task will exit 
@@ -73,8 +75,8 @@ num_endpoints=$(sudo jq .overall_summary.audio_stats.num_endpoints run_summary.j
 audio_files_passed=$(sudo jq .overall_summary.file_stats.passed run_summary.json)
 audio_files_total=$(sudo jq .overall_summary.file_stats.total run_summary.json)
 if [ $? != 0 ]; then
-    echo ERROR: Container did not start properly or speech-batch-kit image directory structure modified
-    exit 1
+    echo "ERROR: Container did not start properly or speech-batch-kit image directory structure modified"
+    EXIT=true
 fi
 
 # verify that speech-batch-kit container ran as expected. container ran as expected if...
@@ -82,13 +84,15 @@ fi
     # all processed audio files passed successfully 
 if [ $num_endpoints = "2" ] && [ $audio_files_passed = $audio_files_total ]
 then 
-    echo INFO: Speech Batch Kit sanity test passed
+    echo "INFO: Speech Batch Kit sanity test passed"
 elif [ $num_endpoints = "2" ] && [ $audio_files_passed != $audio_files_total ] 
 then
-    echo ERROR: Speech Batch Kit sanity test failed. $audio_files_passed out of $audio_files_total audio files were successfully processed
+    echo "ERROR: Speech Batch Kit sanity test failed. $audio_files_passed out of $audio_files_total audio files were successfully processed"
+    EXIT=true
 elif [ $num_endpoints != "2" ] && [ $audio_files_passed = $audio_files_total ]
 then 
-    echo ERROR: Speech Batch Kit sanity test failed. $num_endpoints (not 2) endpoint was used to process audio files
+    echo "ERROR: Speech Batch Kit sanity test failed. $num_endpoints (not 2) endpoint was used to process audio files"
+    EXIT=true
 fi
 popd
 
@@ -97,4 +101,10 @@ popd
 sudo rm -rf $temp_vol/logs $temp_vol/transcriptions 
 docker stop $stt_on_prem_1
 docker stop $stt_on_prem_2
-echo INFO: Deleted bind mount directory and stopped on-premise speech-to-text Docker containers
+echo "INFO: Deleted bind mount directory and stopped on-premise speech-to-text Docker containers"
+
+# exit pipeline if error occurred during sanity test
+if [ $EXIT = true ]
+then 
+    exit 1
+fi
